[theme]
primaryColor = "#444444"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#161B22"
textColor = "#ffffff"

[server]
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false